#!/bin/sh
#
# kea_run4
#
# part of FreeSense (https://www.freesense.org)
# Copyright (c) 2004-2026 The FreeSense Project
# All rights reserved.
#
SCRIPT_BASES="/conf/kea4_scripts.d /cf/conf/kea4_scripts.d"

for _base in ${SCRIPT_BASES}; do
	if [ -d "${_base}" ]; then
		for _script in ${_base}/*; do
			if [ -f "${_script}" -a -x "${_script}" ]; then
				/bin/sh ${_script} $@
			fi
		done
		break # first base match wins
	fi
done
